package main

import (
	"math"
	"math/rand"
	"strings"
	"time"

	"github.com/charmbracelet/lipgloss"
)

// ---- sprites ------------------------------------------------------------

// Right-facing sprites; left-facing ones are generated by mirroring.
var spritesRight = [][]string{
	{"><>"},
	{"><(((º>"},
	{"  ,--.  ", "><(((º> ", "  `--'  "},
}

var mirrorMap = map[rune]rune{'>': '<', '<': '>', '(': ')', ')': '(', '/': '\\', '\\': '/', ',': '.', '`': '\''}

func mirror(lines []string) []string {
	out := make([]string, len(lines))
	for i, l := range lines {
		rs := []rune(l)
		for a, b := 0, len(rs)-1; a < b; a, b = a+1, b-1 {
			rs[a], rs[b] = rs[b], rs[a]
		}
		for k, r := range rs {
			if m, ok := mirrorMap[r]; ok {
				rs[k] = m
			}
		}
		out[i] = string(rs)
	}
	return out
}

var spritesLeft = func() [][]string {
	out := make([][]string, len(spritesRight))
	for i, s := range spritesRight {
		out[i] = mirror(s)
	}
	return out
}()

// ---- entities -----------------------------------------------------------

type fish struct {
	x, y   float64
	baseVx float64
	right  bool
	kind   int
	color  lipgloss.Color
}

func (f *fish) sprite() []string {
	if f.right {
		return spritesRight[f.kind]
	}
	return spritesLeft[f.kind]
}

func (f *fish) size() (int, int) {
	s := f.sprite()
	return len([]rune(s[0])), len(s)
}

type bubble struct {
	x, y, vy float64
	big      bool
}

type food struct{ x, y float64 }

type crab struct {
	x     float64
	right bool
}

type cell struct {
	r      rune
	fg, bg lipgloss.Color
}

const (
	crabRune    = `\(°o°)/`
	crabRuneAlt = `/(°o°)\`
	crabColor   = lipgloss.Color("#ff6b4a")
)

// Tank is the little ecosystem at the bottom of the dashboard. Its inhabitants
// react to live system stats: fish swim faster as CPU rises, the school grows
// with RAM, bubbles stream with network I/O, and the crab hustles under load.
type Tank struct {
	w, h    int
	fish    []*fish
	bubbles []*bubble
	foods   []*food
	weeds   []weed
	stars   []int
	crab    crab
	rng     *rand.Rand
	t       float64 // animation clock (seconds)

	extra         int // user-requested extra fish (+/-)
	happy         float64
	cpu, ram, net float64
}

type weed struct{ x, h int }

func NewTank() *Tank {
	return &Tank{rng: rand.New(rand.NewSource(time.Now().UnixNano())), happy: 80, crab: crab{x: 4, right: true}}
}

// Happiness is 0..100: high while the machine is calm, low under heavy load.
func (t *Tank) Happiness() float64 { return t.happy }

// SetStats feeds fresh readings into the ecosystem.
func (t *Tank) SetStats(cpu, ram, net float64) {
	t.cpu, t.ram, t.net = cpu, ram, net
	t.syncPopulation()
}

// AdjustFish adds/removes fish beyond the RAM-driven baseline.
func (t *Tank) AdjustFish(d int) {
	t.extra = clampInt(t.extra+d, -2, 10)
	t.syncPopulation()
}

// Feed drops a few food flakes from the surface.
func (t *Tank) Feed() {
	w := max(t.w, 10)
	for i := 0; i < 6 && len(t.foods) < 30; i++ {
		t.foods = append(t.foods, &food{x: t.rng.Float64() * float64(w-1), y: 1 - t.rng.Float64()*3})
	}
}

// Resize updates the tank dimensions and keeps inhabitants in bounds.
func (t *Tank) Resize(w, h int) {
	if w == t.w && h == t.h {
		return
	}
	t.w, t.h = w, h
	for _, f := range t.fish {
		fw, fh := f.size()
		f.x = clampF(f.x, 0, float64(max(0, w-fw)))
		f.y = clampF(f.y, 1, float64(max(1, h-1-fh)))
	}
	t.initDecor()
}

func (t *Tank) initDecor() {
	t.weeds, t.stars = t.weeds[:0], t.stars[:0]
	if t.w < 8 {
		return
	}
	for i := 0; i < max(1, t.w/18); i++ {
		t.weeds = append(t.weeds, weed{x: t.rng.Intn(t.w), h: 2 + t.rng.Intn(3)})
	}
	for i := 0; i < max(1, t.w/30); i++ {
		t.stars = append(t.stars, t.rng.Intn(t.w))
	}
}

func (t *Tank) syncPopulation() {
	target := clampInt(3+int(t.ram/100*7)+t.extra, 1, 18)
	for len(t.fish) < target {
		t.addFish()
	}
	if len(t.fish) > target {
		t.fish = t.fish[:target]
	}
}

func (t *Tank) addFish() {
	w, h := t.w, t.h
	if w <= 0 {
		w = 40
	}
	if h <= 0 {
		h = 12
	}
	kind := t.rng.Intn(len(spritesRight))
	if kind == 2 && h < 8 {
		kind = 1
	}
	f := &fish{
		x:      t.rng.Float64() * float64(max(1, w-10)),
		y:      1 + t.rng.Float64()*float64(max(1, h-5)),
		baseVx: 3 + t.rng.Float64()*6,
		kind:   kind,
		color:  th.Fish[t.rng.Intn(len(th.Fish))],
		right:  t.rng.Intn(2) == 0,
	}
	t.fish = append(t.fish, f)
}

// RefreshTheme re-colours the school after a theme change.
func (t *Tank) RefreshTheme() {
	for _, f := range t.fish {
		f.color = th.Fish[t.rng.Intn(len(th.Fish))]
	}
}

// Update advances the animation by dt seconds.
func (t *Tank) Update(dt float64) {
	t.t += dt
	if t.w <= 0 || t.h <= 0 {
		return
	}
	speed := 1 + t.cpu/100*3 // fish dart up to 4x faster at full CPU load

	// Food falls and is eaten.
	keptFood := t.foods[:0]
	for _, fd := range t.foods {
		fd.y += 3 * dt
		if fd.y < float64(t.h-1) {
			keptFood = append(keptFood, fd)
		}
	}
	t.foods = keptFood

	for _, f := range t.fish {
		fw, fh := f.size()
		cx, cy := f.x+float64(fw)/2, f.y+float64(fh)/2
		mul := 1.0
		if fd := t.nearestFood(cx, cy); fd != nil {
			f.right = fd.x > cx
			mul = 1.6
			f.y += clampF(fd.y-cy, -1, 1) * 3 * dt
		} else if t.rng.Float64() < 0.03 {
			f.y += t.rng.Float64()*2 - 1
		}
		f.y = clampF(f.y, 1, float64(max(1, t.h-1-fh)))

		v := f.baseVx * speed * mul
		if f.right {
			f.x += v * dt
		} else {
			f.x -= v * dt
		}
		switch {
		case f.x < 0:
			f.x, f.right = 0, true
		case f.x+float64(fw) > float64(t.w):
			f.x, f.right = float64(max(0, t.w-fw)), false
		}
	}

	// Eating.
	keptFood = t.foods[:0]
	for _, fd := range t.foods {
		eaten := false
		for _, f := range t.fish {
			fw, fh := f.size()
			if math.Abs(f.x+float64(fw)/2-fd.x) <= float64(fw)/2+1 && math.Abs(f.y+float64(fh)/2-fd.y) <= float64(fh)/2+1 {
				eaten = true
				t.happy = math.Min(100, t.happy+3)
				break
			}
		}
		if !eaten {
			keptFood = append(keptFood, fd)
		}
	}
	t.foods = keptFood

	// The crab scuttles faster when the CPU works hard.
	cs := 2 + t.cpu/100*5
	if t.crab.right {
		t.crab.x += cs * dt
	} else {
		t.crab.x -= cs * dt
	}
	if t.crab.x < 0 {
		t.crab.x, t.crab.right = 0, true
	} else if lim := float64(t.w - 7); t.crab.x > lim {
		t.crab.x, t.crab.right = math.Max(0, lim), false
	}
	if t.rng.Float64() < 0.004 {
		t.crab.right = !t.crab.right
	}

	// Bubbles rise from the floor; spawn rate scales with network activity.
	spawnProb := 0.04 + math.Min(t.net/600, 0.45)
	if t.rng.Float64() < spawnProb {
		t.bubbles = append(t.bubbles, &bubble{
			x:   t.rng.Float64() * float64(t.w),
			y:   float64(t.h - 2),
			vy:  4 + t.rng.Float64()*4,
			big: t.rng.Intn(4) == 0,
		})
	}
	kept := t.bubbles[:0]
	for _, b := range t.bubbles {
		b.y -= b.vy * dt
		b.x += math.Sin(b.y) * 0.15
		if b.y > 1 {
			kept = append(kept, b)
		}
	}
	t.bubbles = kept

	// Mood: calm machine -> happy fish.
	target := 100 - math.Max(0, t.cpu-40)*1.4 - math.Max(0, t.ram-75)*1.2
	t.happy += (clampF(target, 0, 100) - t.happy) * math.Min(1, 0.15*dt)
}

func (t *Tank) nearestFood(cx, cy float64) *food {
	var best *food
	bd := math.MaxFloat64
	for _, fd := range t.foods {
		if d := math.Abs(fd.x-cx) + math.Abs(fd.y-cy)*2; d < bd {
			best, bd = fd, d
		}
	}
	return best
}

// Render paints the current frame as exactly t.h rows of t.w visible columns.
func (t *Tank) Render() string {
	w, h := max(1, t.w), max(1, t.h)

	grid := make([][]cell, h)
	for y := range grid {
		rowBg := lerpColor(th.WaterTop, th.WaterBot, float64(y)/float64(max(1, h-1)))
		grid[y] = make([]cell, w)
		for x := range grid[y] {
			bg := rowBg
			// Slow, drifting light rays that fade with depth.
			if depth := 1 - float64(y)/float64(h); depth > 0.15 {
				if v := math.Sin((float64(x)+float64(y)*0.7)*0.33 + t.t*0.35); v > 0.82 {
					bg = lerpColor(rowBg, th.Ray, 0.16*depth*(v-0.82)/0.18)
				}
			}
			grid[y][x] = cell{r: ' ', bg: bg}
		}
	}
	put := func(x, y int, r rune, fg lipgloss.Color) {
		if x >= 0 && x < w && y >= 0 && y < h {
			grid[y][x].r, grid[y][x].fg = r, fg
		}
	}

	// Surface waves.
	for x := 0; x < w; x++ {
		r := '~'
		if math.Sin(float64(x)*0.6+t.t*2.2) > 0.3 {
			r = '≈'
		}
		put(x, 0, r, th.Ray)
	}
	// Sandy floor.
	for x := 0; x < w; x++ {
		r := '▒'
		if (x*7+3)%5 == 0 {
			r = '░'
		}
		put(x, h-1, r, th.Sand)
	}
	// Seaweed swaying up from the floor.
	phase := int(t.t * 1.6)
	for _, s := range t.weeds {
		for i := 0; i < s.h; i++ {
			r := '('
			if (i+phase)%2 == 1 {
				r = ')'
			}
			put(s.x, h-2-i, r, th.Weed)
		}
	}
	// Starfish.
	for _, x := range t.stars {
		put(x, h-2, '*', th.Warn)
	}
	// Crab.
	cr := crabRune
	if int(t.t*3)%2 == 1 {
		cr = crabRuneAlt
	}
	for i, r := range []rune(cr) {
		put(int(t.crab.x)+i, h-2, r, crabColor)
	}
	// Bubbles.
	for _, b := range t.bubbles {
		r := '°'
		if b.big {
			r = 'o'
		}
		if y := int(b.y); y < h-1 {
			put(int(b.x), y, r, th.Bubble)
		}
	}
	// Food.
	for _, fd := range t.foods {
		put(int(fd.x), int(fd.y), '•', th.Food)
	}
	// Fish, drawn last so they sit on top. Spaces in sprites are transparent.
	for _, f := range t.fish {
		fg := f.color
		if t.cpu > 85 {
			fg = th.Bad // the whole school panics under heavy load
		}
		for dy, line := range f.sprite() {
			for dx, r := range []rune(line) {
				if r != ' ' {
					put(int(f.x)+dx, int(f.y)+dy, r, fg)
				}
			}
		}
	}

	lines := make([]string, h)
	for y := 0; y < h; y++ {
		lines[y] = renderTankLine(grid[y])
	}
	return strings.Join(lines, "\n")
}

// renderTankLine turns a row of cells into a styled string, coalescing runs of
// identical colours to keep ANSI output small.
func renderTankLine(cells []cell) string {
	var b strings.Builder
	for i := 0; i < len(cells); {
		j := i
		fg, bg := cells[i].fg, cells[i].bg
		var seg strings.Builder
		for j < len(cells) && cells[j].fg == fg && cells[j].bg == bg {
			seg.WriteRune(cells[j].r)
			j++
		}
		b.WriteString(sty(fg, bg).Render(seg.String()))
		i = j
	}
	return b.String()
}

func clampF(v, lo, hi float64) float64 {
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}
